language: r
before_install: 
  - cd Rcurses
cache: packages
pandoc: false
addons:
  apt:
    packages:
      - libncurses5-dev

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
  
